name: dexfolio_dev
services:
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
    container_name: dx-postgres-dev
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  redis:
    extends:
      file: docker-compose.yml
      service: redis
    container_name: dx-redis-dev
    ports:
      - ${REDIS_PORT:-6379}:6379

volumes:
  postgres:
